name: news_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0-26.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Router
  go_router: ^14.2.3

  # code generator
  freezed_annotation: ^2.4.4

  # state managment
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # api
  retrofit: ^4.1.0

  # db
  floor: ^1.5.0
  sqflite: ^2.3.3+1

  # service locator
  get_it: ^7.7.0

  # dateFormat
  intl: ^0.19.0

  #Hooks
  flutter_hooks: ^0.20.5

  # cached image
  cached_network_image: ^3.4.0

  # Dio
  dio: ^5.5.0+1

  # Comparing objects
  equatable: ^2.0.5

  # Shimmer effect
  shimmer: ^3.0.0
  freezed: ^2.5.7
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.2
  floor_generator: ^1.5.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700